sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t stylianosrigas/docker-react -f Dockerfile.dev .

script:
  - docker run stylianosrigas/docker-react npm run test -- --coverage
